export default [
    {
        files: ["**/*.js", "**/*.jsx", "**/*.ts", "**/*.tsx", "**/*.mjs", "**/*.cjs", "**/*.vue"],
        rules: {
          "valid-typeof": ["error"],
          "use-isnan": ["error"],
          "require-yield": ["error"],
          "no-with": ["error"],
          "no-useless-escape": ["error"],
          "no-useless-catch": ["error"],
          "no-useless-backreference": ["error"],
          "no-unused-vars": ["error"],
          "no-unused-private-class-members": ["error"],
          "no-unused-labels": ["error"],
          "no-unsafe-optional-chaining": ["error"],
          "no-unsafe-negation": ["error"],
          "no-unsafe-finally": ["error"],
          "no-unreachable": ["error"],
          "no-unexpected-multiline": ["error"],
          "no-undef": ["error"],
          "no-this-before-super": ["error"],
          "no-sparse-arrays": ["error"],
          "no-shadow-restricted-names": ["error"],
          "no-setter-return": ["error"],
          "no-self-assign": ["error"],
          "no-regex-spaces": ["error"],
          "no-redeclare": ["error"],
          "no-prototype-builtins": ["error"],
          "no-octal": ["error"],
          "no-obj-calls": ["error"],
          "no-nonoctal-decimal-escape": ["error"],
          "no-new-native-nonconstructor": ["error"],
          "no-misleading-character-class": ["error"],
          "no-loss-of-precision": ["error"],
          "no-irregular-whitespace": ["error"],
          "no-invalid-regexp": ["error"],
          "no-import-assign": ["error"],
          "no-global-assign": ["error"],
          "no-func-assign": ["error"],
          "no-fallthrough": ["error"],
          "no-extra-boolean-cast": ["error"],
          "no-ex-assign": ["error"],
          "no-empty-static-block": ["error"],
          "no-empty-pattern": ["error"],
          "no-empty-character-class": ["error"],
          "no-empty": ["error"],
          "no-duplicate-case": ["error"],
          "no-dupe-keys": ["error"],
          "no-dupe-else-if": ["error"],
          "no-dupe-class-members": ["error"],
          "no-dupe-args": ["error"],
          "no-delete-var": ["error"],
          "no-debugger": ["error"],
          "no-control-regex": ["error"],
          "no-constant-condition": ["error"],
          "no-constant-binary-expression": ["error"],
          "no-const-assign": ["error"],
          "no-cond-assign": ["error", "except-parens"],
          "no-compare-neg-zero": ["error"],
          "no-class-assign": ["error"],
          "no-case-declarations": ["error"],
          "no-async-promise-executor": ["error"],
          "getter-return": ["error"],
          "for-direction": ["error"],
          "constructor-super": ["error"],
        }
    }
];
