"""
Tests for .claude/skills/seed-sync/build-seed-bundle.py (and devops/build-seed-bundle.py)

Tests build_bundle() by patching the DATA_DIR and OUTPUT_FILE to use temp directories.
"""

import importlib.util
import json
import os
import sys
import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch

# ---------------------------------------------------------------------------
# Load the module under test (use the skills-sync copy added in this PR)
# ---------------------------------------------------------------------------
SCRIPT_PATH = os.path.join(
    os.path.dirname(__file__),
    "../../.claude/skills/seed-sync/build-seed-bundle.py",
)
spec = importlib.util.spec_from_file_location("build_seed_bundle", SCRIPT_PATH)
build_seed_bundle = importlib.util.module_from_spec(spec)
spec.loader.exec_module(build_seed_bundle)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def write_year_file(data_dir, year, entries):
    """Write a spot-history-{year}.json file into data_dir."""
    path = os.path.join(data_dir, f"spot-history-{year}.json")
    with open(path, "w") as f:
        json.dump(entries, f)
    return path


def read_output(output_file):
    """Read and return the text of the generated JS bundle."""
    with open(output_file) as f:
        return f.read()


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------


class TestBuildBundle(unittest.TestCase):

    def setUp(self):
        """Create a fresh temp dir for each test."""
        self._tmpdir = tempfile.TemporaryDirectory()
        self.data_dir = self._tmpdir.name
        self.output_file = os.path.join(self.data_dir, "spot-history-bundle.js")

    def tearDown(self):
        self._tmpdir.cleanup()

    def run_build_bundle(self):
        """Run build_bundle() with DATA_DIR and OUTPUT_FILE patched to temp dirs."""
        with patch.object(build_seed_bundle, "DATA_DIR", self.data_dir), \
             patch.object(build_seed_bundle, "OUTPUT_FILE", self.output_file):
            build_seed_bundle.build_bundle()

    # --- Basic output file generation ---

    def test_empty_data_dir_generates_output_file(self):
        """With no year files, output file is still created (empty bundle)."""
        self.run_build_bundle()
        self.assertTrue(os.path.exists(self.output_file))

    def test_output_file_contains_loader_call(self):
        """Output always contains window._loadSpotSeedBundle(...)."""
        self.run_build_bundle()
        content = read_output(self.output_file)
        self.assertIn("window._loadSpotSeedBundle(", content)

    def test_output_file_contains_auto_generated_comment(self):
        """Output file starts with auto-generated comment."""
        self.run_build_bundle()
        content = read_output(self.output_file)
        self.assertTrue(content.startswith("// Auto-generated by"))

    def test_output_file_contains_entry_count_comment(self):
        """Output file includes entry count and year count in header comment."""
        write_year_file(self.data_dir, 2020, [
            {"spot": 25.50, "metal": "silver", "timestamp": "2020-03-15 12:00:00"},
        ])
        self.run_build_bundle()
        content = read_output(self.output_file)
        self.assertIn("entries", content)
        self.assertIn("years", content)

    # --- Single year file ---

    def test_single_year_single_entry(self):
        """Single year file with one entry appears in the bundle."""
        write_year_file(self.data_dir, 2020, [
            {"spot": 25.50, "metal": "silver", "timestamp": "2020-03-15 12:00:00"},
        ])
        self.run_build_bundle()
        content = read_output(self.output_file)
        data_json = content.split("window._loadSpotSeedBundle(")[1].rstrip(");\n")
        bundle = json.loads(data_json)
        self.assertIn("2020", bundle)
        self.assertIn("silver", bundle["2020"])
        self.assertEqual(bundle["2020"]["silver"], [["03-15", 25.50]])

    def test_timestamp_extraction_yields_mm_dd(self):
        """Timestamps 'YYYY-MM-DD HH:MM:SS' are reduced to 'MM-DD'."""
        write_year_file(self.data_dir, 2021, [
            {"spot": 1800.0, "metal": "gold", "timestamp": "2021-07-04 09:00:00"},
        ])
        self.run_build_bundle()
        content = read_output(self.output_file)
        data_json = content.split("window._loadSpotSeedBundle(")[1].rstrip(");\n")
        bundle = json.loads(data_json)
        self.assertEqual(bundle["2021"]["gold"][0][0], "07-04")

    def test_spot_price_rounded_to_two_decimals(self):
        """Spot prices are rounded to 2 decimal places."""
        write_year_file(self.data_dir, 2022, [
            {"spot": 24.5678, "metal": "silver", "timestamp": "2022-01-01 00:00:00"},
        ])
        self.run_build_bundle()
        content = read_output(self.output_file)
        data_json = content.split("window._loadSpotSeedBundle(")[1].rstrip(");\n")
        bundle = json.loads(data_json)
        self.assertEqual(bundle["2022"]["silver"][0][1], 24.57)

    def test_integer_spot_price_preserved(self):
        """Integer-like spot prices are preserved as floats (no extra decimals)."""
        write_year_file(self.data_dir, 2022, [
            {"spot": 30.0, "metal": "silver", "timestamp": "2022-06-15 00:00:00"},
        ])
        self.run_build_bundle()
        content = read_output(self.output_file)
        data_json = content.split("window._loadSpotSeedBundle(")[1].rstrip(");\n")
        bundle = json.loads(data_json)
        self.assertEqual(bundle["2022"]["silver"][0][1], 30.0)

    # --- Multiple metals in one year ---

    def test_multiple_metals_in_same_year(self):
        """Multiple metals in the same year file are grouped by metal."""
        write_year_file(self.data_dir, 2023, [
            {"spot": 25.0, "metal": "silver", "timestamp": "2023-01-10 00:00:00"},
            {"spot": 1900.0, "metal": "gold", "timestamp": "2023-01-10 00:00:00"},
            {"spot": 1000.0, "metal": "platinum", "timestamp": "2023-01-10 00:00:00"},
        ])
        self.run_build_bundle()
        content = read_output(self.output_file)
        data_json = content.split("window._loadSpotSeedBundle(")[1].rstrip(");\n")
        bundle = json.loads(data_json)
        self.assertIn("silver", bundle["2023"])
        self.assertIn("gold", bundle["2023"])
        self.assertIn("platinum", bundle["2023"])

    def test_multiple_entries_same_metal_appended(self):
        """Multiple entries for the same metal in one year are all included."""
        write_year_file(self.data_dir, 2023, [
            {"spot": 25.0, "metal": "silver", "timestamp": "2023-01-10 00:00:00"},
            {"spot": 26.5, "metal": "silver", "timestamp": "2023-02-20 00:00:00"},
            {"spot": 24.0, "metal": "silver", "timestamp": "2023-03-30 00:00:00"},
        ])
        self.run_build_bundle()
        content = read_output(self.output_file)
        data_json = content.split("window._loadSpotSeedBundle(")[1].rstrip(");\n")
        bundle = json.loads(data_json)
        self.assertEqual(len(bundle["2023"]["silver"]), 3)

    # --- Multiple years ---

    def test_multiple_year_files_all_included(self):
        """Multiple year files are all merged into the bundle."""
        for year in [2019, 2020, 2021]:
            write_year_file(self.data_dir, year, [
                {"spot": 20.0 + year - 2019, "metal": "silver",
                 "timestamp": f"{year}-06-01 00:00:00"},
            ])
        self.run_build_bundle()
        content = read_output(self.output_file)
        data_json = content.split("window._loadSpotSeedBundle(")[1].rstrip(");\n")
        bundle = json.loads(data_json)
        self.assertIn("2019", bundle)
        self.assertIn("2020", bundle)
        self.assertIn("2021", bundle)

    def test_missing_year_files_are_skipped_silently(self):
        """Years with no file are silently skipped — only present years in bundle."""
        write_year_file(self.data_dir, 2020, [
            {"spot": 25.0, "metal": "silver", "timestamp": "2020-01-01 00:00:00"},
        ])
        # No 2019 file, no 2021 file
        self.run_build_bundle()
        content = read_output(self.output_file)
        data_json = content.split("window._loadSpotSeedBundle(")[1].rstrip(");\n")
        bundle = json.loads(data_json)
        self.assertNotIn("2019", bundle)
        self.assertIn("2020", bundle)
        self.assertNotIn("2021", bundle)

    # --- Entry filtering / missing fields ---

    def test_entry_missing_spot_is_skipped(self):
        """Entries without 'spot' field are skipped."""
        write_year_file(self.data_dir, 2020, [
            {"metal": "silver", "timestamp": "2020-01-01 00:00:00"},  # no spot
            {"spot": 25.0, "metal": "silver", "timestamp": "2020-06-01 00:00:00"},
        ])
        self.run_build_bundle()
        content = read_output(self.output_file)
        data_json = content.split("window._loadSpotSeedBundle(")[1].rstrip(");\n")
        bundle = json.loads(data_json)
        self.assertEqual(len(bundle["2020"]["silver"]), 1)

    def test_entry_missing_metal_is_skipped(self):
        """Entries without 'metal' field are skipped."""
        write_year_file(self.data_dir, 2020, [
            {"spot": 25.0, "timestamp": "2020-01-01 00:00:00"},  # no metal
            {"spot": 26.0, "metal": "silver", "timestamp": "2020-06-01 00:00:00"},
        ])
        self.run_build_bundle()
        content = read_output(self.output_file)
        data_json = content.split("window._loadSpotSeedBundle(")[1].rstrip(");\n")
        bundle = json.loads(data_json)
        self.assertEqual(len(bundle["2020"]["silver"]), 1)

    def test_entry_missing_timestamp_is_skipped(self):
        """Entries without 'timestamp' field are skipped."""
        write_year_file(self.data_dir, 2020, [
            {"spot": 25.0, "metal": "silver"},  # no timestamp
            {"spot": 26.0, "metal": "silver", "timestamp": "2020-06-01 00:00:00"},
        ])
        self.run_build_bundle()
        content = read_output(self.output_file)
        data_json = content.split("window._loadSpotSeedBundle(")[1].rstrip(");\n")
        bundle = json.loads(data_json)
        self.assertEqual(len(bundle["2020"]["silver"]), 1)

    def test_entry_with_zero_spot_is_skipped(self):
        """Entries with spot=0 are falsy and thus skipped."""
        write_year_file(self.data_dir, 2020, [
            {"spot": 0, "metal": "silver", "timestamp": "2020-01-01 00:00:00"},  # zero = falsy
            {"spot": 25.0, "metal": "silver", "timestamp": "2020-06-01 00:00:00"},
        ])
        self.run_build_bundle()
        content = read_output(self.output_file)
        data_json = content.split("window._loadSpotSeedBundle(")[1].rstrip(");\n")
        bundle = json.loads(data_json)
        self.assertEqual(len(bundle["2020"]["silver"]), 1)

    def test_all_entries_invalid_year_not_in_bundle(self):
        """If all entries in a year are invalid, the year is excluded from bundle."""
        write_year_file(self.data_dir, 2020, [
            {"metal": "silver", "timestamp": "2020-01-01 00:00:00"},  # no spot
            {"spot": 25.0, "timestamp": "2020-06-01 00:00:00"},  # no metal
        ])
        self.run_build_bundle()
        content = read_output(self.output_file)
        data_json = content.split("window._loadSpotSeedBundle(")[1].rstrip(");\n")
        bundle = json.loads(data_json)
        self.assertNotIn("2020", bundle)

    # --- Non-list input ---

    def test_non_list_year_file_is_skipped(self):
        """Year files that are not JSON arrays (e.g., dicts) are skipped entirely."""
        path = os.path.join(self.data_dir, "spot-history-2020.json")
        with open(path, "w") as f:
            json.dump({"not": "a list"}, f)
        self.run_build_bundle()
        content = read_output(self.output_file)
        data_json = content.split("window._loadSpotSeedBundle(")[1].rstrip(");\n")
        bundle = json.loads(data_json)
        self.assertNotIn("2020", bundle)

    def test_null_year_file_is_skipped(self):
        """Year files containing JSON null are skipped (not a list)."""
        path = os.path.join(self.data_dir, "spot-history-2020.json")
        with open(path, "w") as f:
            json.dump(None, f)
        self.run_build_bundle()
        content = read_output(self.output_file)
        data_json = content.split("window._loadSpotSeedBundle(")[1].rstrip(");\n")
        bundle = json.loads(data_json)
        self.assertNotIn("2020", bundle)

    # --- Output format ---

    def test_bundle_is_valid_json_inside_loader(self):
        """The data argument to window._loadSpotSeedBundle() is valid JSON."""
        write_year_file(self.data_dir, 2022, [
            {"spot": 22.0, "metal": "silver", "timestamp": "2022-05-05 00:00:00"},
        ])
        self.run_build_bundle()
        content = read_output(self.output_file)
        # Extract JSON between the parentheses of _loadSpotSeedBundle(...)
        start = content.index("window._loadSpotSeedBundle(") + len("window._loadSpotSeedBundle(")
        end = content.rindex(");")
        data_str = content[start:end]
        parsed = json.loads(data_str)
        self.assertIsInstance(parsed, dict)

    def test_bundle_uses_compact_json_no_spaces(self):
        """Bundle JSON is compact (no extra spaces) to minimize file size."""
        write_year_file(self.data_dir, 2022, [
            {"spot": 22.0, "metal": "silver", "timestamp": "2022-05-05 00:00:00"},
        ])
        self.run_build_bundle()
        content = read_output(self.output_file)
        start = content.index("window._loadSpotSeedBundle(") + len("window._loadSpotSeedBundle(")
        end = content.rindex(");")
        data_str = content[start:end]
        # Compact JSON should not have ": " (colon-space) or ", " (comma-space)
        self.assertNotIn(": ", data_str)
        self.assertNotIn(", ", data_str)

    def test_output_ends_with_loader_call_terminator(self):
        """Output file ends with the ');\n' terminator of the loader call."""
        self.run_build_bundle()
        content = read_output(self.output_file)
        self.assertTrue(content.rstrip("\n").endswith(");"))

    def test_output_overwrites_existing_file(self):
        """Calling build_bundle() twice overwrites, not appends to, the output file."""
        write_year_file(self.data_dir, 2020, [
            {"spot": 25.0, "metal": "silver", "timestamp": "2020-01-01 00:00:00"},
        ])
        self.run_build_bundle()
        first_content = read_output(self.output_file)
        self.run_build_bundle()
        second_content = read_output(self.output_file)
        self.assertEqual(first_content, second_content)

    # --- Year range boundary ---

    def test_start_year_constant(self):
        """START_YEAR constant is 1968."""
        self.assertEqual(build_seed_bundle.START_YEAR, 1968)

    def test_end_year_constant_present(self):
        """END_YEAR constant is defined and reasonable (>= 2024)."""
        self.assertGreaterEqual(build_seed_bundle.END_YEAR, 2024)

    # --- Entry counting ---

    def test_total_entry_count_in_comment_matches_data(self):
        """Comment line entry count matches the actual number of valid entries."""
        write_year_file(self.data_dir, 2020, [
            {"spot": 25.0, "metal": "silver", "timestamp": "2020-01-01 00:00:00"},
            {"spot": 26.0, "metal": "silver", "timestamp": "2020-06-01 00:00:00"},
            {"spot": 1800.0, "metal": "gold", "timestamp": "2020-03-15 00:00:00"},
        ])
        self.run_build_bundle()
        content = read_output(self.output_file)
        # Second line: "// 3 entries across 1 years"
        lines = content.split("\n")
        comment_line = lines[1]
        self.assertIn("3", comment_line)
        self.assertIn("1", comment_line)

    def test_skipped_entries_not_counted(self):
        """Invalid (skipped) entries do not appear in the total count comment."""
        write_year_file(self.data_dir, 2020, [
            {"spot": 25.0, "metal": "silver", "timestamp": "2020-01-01 00:00:00"},  # valid
            {"metal": "silver", "timestamp": "2020-02-01 00:00:00"},  # no spot — skipped
        ])
        self.run_build_bundle()
        content = read_output(self.output_file)
        lines = content.split("\n")
        comment_line = lines[1]
        # Only 1 valid entry
        self.assertIn("1", comment_line)

    # --- Regression: bundle keys are integers (JSON parse round-trip) ---

    def test_year_keys_are_strings_in_parsed_bundle(self):
        """After JSON parsing, year keys are strings (JSON spec: object keys are always strings).
        The Python int keys from the internal dict become string keys after json.dumps → json.loads."""
        write_year_file(self.data_dir, 2022, [
            {"spot": 22.0, "metal": "silver", "timestamp": "2022-06-01 00:00:00"},
        ])
        self.run_build_bundle()
        content = read_output(self.output_file)
        data_json = content.split("window._loadSpotSeedBundle(")[1].rstrip(");\n")
        bundle = json.loads(data_json)
        # JSON keys are strings, but in the original Python dict they were ints
        # After json.dumps → json.loads they become strings
        keys = list(bundle.keys())
        # Keys should be "2022" (string after JSON round-trip)
        self.assertIn("2022", keys)


if __name__ == "__main__":
    unittest.main()