#!/usr/bin/env python3
"""
Build a compact JS seed bundle from spot-history year files.

Reads data/spot-history-{year}.json (1968–current) and generates
data/spot-history-bundle.js — a single <script>-loadable file that
pre-populates historicalDataCache so charts work on file:// protocol
where fetch() and XHR are blocked by Chrome security.

Compact format groups entries by year → metal → [[MM-DD, price], ...].
The JS loader in spot.js expands these back into full cache entries.

Usage:
    python3 devops/build-seed-bundle.py

Run from project root. Output: data/spot-history-bundle.js
"""

import json
import os
import sys
from collections import defaultdict

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_DIR = os.path.join(PROJECT_ROOT, "data")
OUTPUT_FILE = os.path.join(DATA_DIR, "spot-history-bundle.js")

START_YEAR = 1968
END_YEAR = 2026  # Update when adding new year files


def build_bundle():
    """Read all year files and produce compact JS bundle."""
    # Structure: { year: { metal: [[MM-DD, price], ...] } }
    bundle = {}
    total_entries = 0

    for year in range(START_YEAR, END_YEAR + 1):
        filepath = os.path.join(DATA_DIR, f"spot-history-{year}.json")
        if not os.path.exists(filepath):
            continue

        with open(filepath, "r") as f:
            entries = json.load(f)

        if not isinstance(entries, list):
            continue

        year_data = defaultdict(list)
        for e in entries:
            if not (e.get("spot") and e.get("metal") and e.get("timestamp")):
                continue
            # Extract MM-DD from timestamp "YYYY-MM-DD HH:MM:SS"
            ts = e["timestamp"]
            mm_dd = ts[5:10]  # "MM-DD"
            year_data[e["metal"]].append([mm_dd, round(e["spot"], 2)])
            total_entries += 1

        if year_data:
            bundle[year] = dict(year_data)

    # Generate JS
    js_data = json.dumps(bundle, separators=(",", ":"))
    js_content = f"// Auto-generated by devops/build-seed-bundle.py — do not edit\n"
    js_content += f"// {total_entries} entries across {len(bundle)} years\n"
    js_content += f"window._loadSpotSeedBundle({js_data});\n"

    with open(OUTPUT_FILE, "w") as f:
        f.write(js_content)

    file_size = os.path.getsize(OUTPUT_FILE)
    print(f"Generated {OUTPUT_FILE}")
    print(f"  {total_entries} entries, {len(bundle)} years")
    print(f"  {file_size:,} bytes ({file_size // 1024}KB)")


if __name__ == "__main__":
    build_bundle()